# Emscripten/WebAssembly build for the browser and Vercel.
PLATFORM = web

include Makefile.common

LIBS = $(COMMON_LIBS) platforms/sdl2
OUTPUT_EXT = .html
WEB_BUILD = build/web
EMXX ?= em++
WEB_CFLAGS = $(COMMON_CFLAGS) $(INCLUDES) -DWEB_BUILD -DGAMEPAD_SUPPORT -fexceptions
# Keep initial browser payload lean. Large factory libraries (samples,
# SR wavetables, instrument banks, external fonts and native title art) are
# useful content, but they are not required to open the tracker and must not
# block startup. They can be added back later as lazy/on-demand libraries.
WEB_PRELOAD = \
	--preload-file packaging/common/projects/grieg-mountain-king-fm.cct@/projects/grieg-mountain-king-fm.cct \
	--preload-file packaging/common/pitch-tables@/pitch-tables \
	--preload-file packaging/common/themes@/themes \
	--preload-file packaging/common/AY_wavetables@/AY_wavetables \
	--preload-file packaging/common/waveforms@/waveforms
WEB_LDFLAGS = -sUSE_SDL=2 -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=256MB \
	-sASYNCIFY=1 \
	-sFORCE_FILESYSTEM=1 -sNO_EXIT_RUNTIME=1 -sEXPORTED_RUNTIME_METHODS=ccall,FS \
	-sDEFAULT_TO_CXX \
	-lidbfs.js \
	$(WEB_PRELOAD)

SOURCES := $(filter-out platforms/sdl2/corelib_mainloop.cpp,$(SOURCES)) \
	platforms/web/corelib_mainloop.cpp

.PHONY: web web-deploy

web:
	@mkdir -p $(WEB_BUILD)
	$(EMXX) $(WEB_CFLAGS) $(SOURCES) $(WEB_LDFLAGS) -o $(WEB_BUILD)/choochootracker.html \
	-sASSERTIONS=1 -sSTACK_SIZE=8388608 -sGL_ASSERTIONS=1
	@cp ../web/index.html $(WEB_BUILD)/index.html
	@cp ../web/wroom.css $(WEB_BUILD)/wroom.css
	@cp ../web/wroom.js $(WEB_BUILD)/wroom.js
	@cp ../web/privacy.html $(WEB_BUILD)/privacy.html

web-deploy: web
	@mkdir -p ../web/dist
	@cp $(WEB_BUILD)/choochootracker.* ../web/dist/
	@cp $(WEB_BUILD)/index.html ../web/dist/
	@cp $(WEB_BUILD)/wroom.css ../web/dist/
	@cp $(WEB_BUILD)/wroom.js ../web/dist/
	@cp $(WEB_BUILD)/privacy.html ../web/dist/
