import fs from "node:fs";
import assert from "node:assert/strict";

const shell = fs.readFileSync("web/wroom.js", "utf8");
const html = fs.readFileSync("web/index.html", "utf8");
const css = fs.readFileSync("web/wroom.css", "utf8");
const app = fs.readFileSync("tracker/src/app.cpp", "utf8");
const song = fs.readFileSync("tracker/src/screens/screen_song.cpp", "utf8");
const audio = fs.readFileSync("tracker/src/audio_manager.cpp", "utf8");

assert.match(app, /webPlaybackTrackPacked/, "Web must read a compact canonical playback snapshot");
assert.match(audio, /webOutputStereoPeaksPacked/, "Web must export real final-output stereo peaks");
assert.match(app, /waveformDisplayGetBitmap\(track\)/, "Song must reuse original waveform glyph");
assert.match(app, /webTrackActivityPacked/, "Song must read native track pitch/mute/clip status");
assert.match(html, /id="songActivityRows"/, "Desktop track monitor missing");
assert.match(html, /id="songActivityMobile"/, "Mobile track monitor expander missing");
assert.match(shell, /updateTrackActivity/, "Track status refresh missing");
assert.match(app, /webTrackAudioScopeHex/, "High-resolution scope must read existing native PCM");
assert.match(shell, /updateTrackScopes/, "Smooth rAF scope refresh missing");
assert.match(shell, /readTrackScope/, "Track scope must decode real 16-bit PCM");
assert.match(shell, /targetGain = 0\.86 \/ peak/, "Scope shape auto-gain missing");
assert.match(shell, /peak < 4 \/ 32768/, "Silence gate must prevent fake waveforms");
assert.match(app, /AUDIO_MONITOR_SAMPLES \* 4 \+ 1/, "Native 16-bit bridge output missing");
assert.match(css, /\.track-activity-row/, "Track monitor styling missing");
assert.match(audio, /webAccumulatePeak/, "Audio callback must collect peak data without allocation");
assert.match(audio, /floatBuffer\[frame \* 2 \+ 1\]/, "Right channel must be measured separately");
assert.match(html, /id="masterPeakL"/, "Global left output meter missing");
assert.match(html, /id="masterPeakR"/, "Global right output meter missing");
assert.match(shell, /updateMasterMeters/, "Global meter must read live output state");
assert.match(app, /chipnomadGetPlaybackStatus/, "Playback bridge must come from canonical PlaybackStatus");
assert.match(song, /webSongChainSummary/, "Song must expose semantic Chain summaries");
assert.match(song, /webSongChainPreview/, "Song must provide canonical Chain/Phrase/Instrument preview");
assert.match(song, /webSongChainInstrumentSearch/, "Search must include every explicit Chain instrument");
assert.match(shell, /entry\.instrumentSearch\.toUpperCase\(\)\.includes\(query\)/,
  "Search must not be limited to two preview instruments");
assert.match(song, /project\.phrases\[phrase\]\.rows\[row\]/, "Preview must inspect real Phrase rows");
assert.match(song, /instrumentName\(/, "Preview must show real instrument names");
assert.match(song, /note\.instrument/, "Preview must read actual instrument references");
assert.match(shell, /entry\.preview/, "Picker must display actual chain content rather than repeated labels");
assert.match(shell, /song-chain-preview/, "Selected Song cell must show the same canonical Chain content");
assert.match(shell, /!entry\.usage && !entry\.steps/, "Picker must suppress unused empty slots by default");
assert.match(html, /id="chainPickerEmpty"/, "Empty search must have a user-visible explanation");
assert.match(song, /webSongFindFreeChain/, "Song picker must assign a genuinely free Chain");

assert.match(html, /id="chainPickerDialog"/, "Chain picker dialog must exist");
assert.match(html, /id="songEditSelected"/, "Touch users need a visible Song editor");
assert.match(html, /id="songMoreRows"/, "Song must expose additional arrangement rows");
assert.match(shell, /ensureSongRowRendered/, "Keyboard navigation must expand Song rows");
assert.match(shell, /songMinimumRows/, "Song row expansion must preserve its visible range");
assert.match(css, /\.song-more-rows/, "Song row-expansion control needs a visible style");
assert.match(html, /id="chainPickerSearch"/, "Chain picker must expose visible search");
assert.match(shell, /songInspectorChooseChain/, "Picker must be the primary inspector action");
assert.match(shell, /updateSongPlaybackVisuals/);
assert.match(shell, /webPlaybackTrackPacked/, "DOM playback state must use the compact bridge");
assert.match(shell, /\}, 50\);/, "Playback visuals must refresh on a bounded loop");
assert.doesNotMatch(shell, /song-cell-meta/, "Song cells must not repeat CHAIN\/EMPTY micro-labels");
assert.match(css, /\.song-cell\.playing/, "Playing cell must have a distinct semantic style");
assert.match(css, /\.song-grid-row\.playing-row/, "Playing row must have a distinct semantic style");
assert.match(css, /\.song-cell\.selected/, "Selection styling must remain independent");
assert.match(css, /\.chain-picker-item/, "Chain picker must have touch-sized semantic choices");

assert.match(app, /webMonitorPianoNotes/, "Native piano monitor must be exposed by Web");
assert.match(app, /monitorPianoNotes\(\)/, "Web piano must use exact native chord pitch mask");
assert.match(html, /id="songActivityPiano"/, "Desktop piano monitor missing");
assert.match(html, /id="songActivityMobilePiano"/, "Mobile piano monitor missing");
assert.match(shell, /updateMonitorPiano/, "Piano keys must reflect native audio state");
assert.match(shell, /webSongToggleTrackMute/, "Native mute control missing from Web");
assert.match(shell, /webSongToggleTrackSolo/, "Native solo control missing from Web");
assert.match(song, /webSongLiveQueuePacked/, "Web must read native queued live actions");
assert.match(shell, /queued-stop/, "Live stop marker missing");
assert.match(shell, /queued-urgent/, "Urgent live launch marker missing");
assert.match(shell, /dataset\.baseAriaLabel/, "Queue accessibility label must preserve original cell reference");
assert.match(shell, /urgent stop queued/, "Queued urgent stop must have an accessible name");
assert.match(shell, /chain launch queued/, "Queued Chain launch must have an accessible name");
assert.match(css, /\.monitor-key\.black\.active/, "Active black piano keys must be visible");
console.log("Song semantic Web contract passed");
